### PR TITLE
Allow config of svn binary location.

### PR DESCRIPTION
**Pull request by ezarko**
Uses atom.config.get() to fetch location of svn and svnversion, and if not set defaults to using path as before.

### CODE REVIEW

**Comment by ezarko** [comment]
I have tested this on my machine and it does work!

**Comment by Arcanemagus** [comment]
It doesn't look like you are defining this configuration anywhere...? You may want to peruse [the documentation](https://atom.io/docs/api/v1.5.3/Config).

**Comment by 0rvar** [comment]
As @Arcanemagus pointed out, the PR lacks changes to the configuration schema. If you could add that, perhaps we could get this merged.

**Comment by 0rvar** [comment]
I am closing this due to inactivity. Feel free to create a new pull request in the future.

**Pull request closed without merging**
